### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by d0rf3n** [ro-abramov/vscode-marks-to-outline#2]
Any way you could add support for any language?

I'm specifically looking for markdown support.

Thanks!

**Comment by ro-abramov** [comment]
Hi @d0rf3n, thanks for submitting the issue, I think this is possible to add it for all languages, I will check how to get all available languages in vscode.

**Comment by d0rf3n** [comment]
Sweet! Keep up the good work.

**Comment by ro-abramov** [comment]
![image](https://user-images.githubusercontent.com/13414557/112299259-af65a280-8ca8-11eb-97ff-5d3ecc12528d.png)
@d0rf3n Hi again, Hope this is what you were looking for. I'll close this issue. In case you need sth else, please create a new one.

Have a good day ;)
